---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: advert-front-secret
  namespace: advert-front
spec:
  encryptedData:
    BACKEND_URL: AgBtHYkLnzLH9QE2WzYMAKhnTOD8rKA6wygdKW4i335BtQBp71oTi7V+IFuKekNCulin8fwlFeQe5WbggmpMTbie28ht4HEwjMnutQnNOTJcNDfo3BsrvR++Ue8jyDiqELcXdFpeESwXXvyrk3y6vo92+IYarBIGhn9VP8yU/e0sdSNIP1+HQEe3S0CmCpt0aDNl17O4L24Fr2abuf1F1uJdruCRx/5yKeSCHCB16urf1BFzWAa+b6zPx8DANWGEGrVVFY4zOgl70Zd11I3ZY4Bk/RKcz0ZiFg2bIsoDhItAqZSJE08tG6A8n9AFUwUBemE5NnlcG9KWZIrpZ977jx8/QiEamz5T093vHZbp1vV0RdIYbMAjhn8D3oMaBkFPc7LHuH29jCfB/3c+T32jBsIuvexUZu/cd0dMYcLfVzRN8QEWq03n763YvXJ4AQS//CrHo1Ph1Zu4oxFhj//1xlhBnn9a2VzlGmI6BU984Hl/UixjZwEGrIFhFVNZrn/MQGxQCxczSHAX9S8FS6yRAnHvuCVqBh8BgUZJ/hF7TcuVemJyUpa7+f5KJTMI2ABNzHMKRiKclzNn7Q/v/kPmasB8TnMlvew1Vxpf92uXi3KNk0i3cMkq09H2mURRqN1OaPNCIsCeDB+hiQb2wQOh0iSWwClXUcrzB/XagH0b06JrjP0A6flP/vhF5K6c1AQcG2Yd9bz0EB77Riq87Q/FBve14YMLqQyaPo+tAlkeF2Xn9TavQV1LhJMLiJBM7xhmKjtP6U65Ug==
    NEXT_PUBLIC_WS_URL: AgAwfUlPp44U4eWdm2YYSb91GxeV1YFsuABag6Gpob/Qjezd8mg1QptThaL95p08gdNPw90gbBeeli5WKnSxhWeMZjXa3Zpw9gpU6cDsqi5P2wqGduCTyixY7w2Jlruw3QaPKaWs2YVo7c0LusqNkHe472lpExmRo3SnSqFMflaaxC7slRZXga5Mmbdfey6bYdYHN0w8WlwjEq8R3X/2jqWFAlTLMe/RZWGf2U/LmR4o9i3L5YWh2862Qat3hDRZ3gRtnCmvdQQ8IJs1vitZK3n9fG6mLMFOA1dmeYei4/8WXvrtlgaYoNJJv3BDw0cm0HO794V8YF4Ewuo6VoErwrcpBtZ3w6OdqneF0MoIZqUxZE4c1nf+qjvp8lpOI3YoKJWPiHdpW6kmkTpZtI6DriXIcmndRK8XYaMj3CBWZJEzx9NZQdBaWV+eG7HSyDzNyQ/cnVZT2jor9goooB4OyMf+gDl+nVg4uYNsxTNlOUIEYWrWFqVq4E0LyFhCBW9WQIuZYt/js20G2B3NxdmwC93OX06d1KE8rm55NO/FtWXJkMyi67MkOH59afzTvcuEoYQgbXvudyNBDbufbBa0SAoYDhxY4dBsgzxizHimTzdIkMk1sRNWhFWSo0oCG2+0Fhlz5dnL1HjJcOzW4raLXcZiCu/a/hbNS7/b8WTn/A0DdesghbQNSYpfpvJZ00dpp70QVXcrGvFA9hzO2Mx0HAq2MCgRSNRcD5pzHcmOxbHXntbJnuWfmrgdKBDNRA==
  template:
    metadata:
      name: advert-front-secret
      namespace: advert-front
    type: Opaque
